"""empty message

Revision ID: 4269bfc56525
Revises: 
Create Date: 2026-09-08 12:26:21.844256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4269bfc56525'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Athletes')
    with op.batch_alter_table('Games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('developer', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('available_platforms', sa.String(length=100), nullable=True))
        batch_op.drop_column('rating')
        batch_op.drop_column('completed')
        batch_op.drop_column('platform')
        batch_op.drop_column('review')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('platform', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), nullable=True))
        batch_op.drop_column('available_platforms')
        batch_op.drop_column('publisher')
        batch_op.drop_column('developer')

    op.create_table('Athletes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=20), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=20), nullable=True),
    sa.Column('jersey', sa.INTEGER(), nullable=True),
    sa.Column('positions', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
